Develop/develop
nakajima-john-shotaro/AIcon_dev pull request #21
Opened 2021-09-07 13:37 UTC by nakajima-john-shotaro

Merged frontend and backend files.

2021-09-07 13:50 UTC, urasakikeisuke requested changes
PythonについてはなるべくPEPに従うようにしてください。

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/communication.py
> +
```suggestion
from waitress import serve
```

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/communication.py
> +
https://qiita.com/shimac/items/557dd5e6b3071ba12f05

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/static/js/functions.js
> +        text : "cute very very long dog. I'm slave on lab",
変更していただけないでしょうか

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/static/js/functions.js
> +        url: "http://slack.tasakilab:8081/",
ここ柔軟に変更できるようにしてください

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/static/js/functions.js
> +            if (r_data["complete"] == false) {
```suggestion
            if (!r_data["complete"] ) {
```

2021-09-07 13:50 UTC, urasakikeisuke commented on aicon/frontend/communication.py
> +    app.run(debug=True, host="0.0.0.0", port=8083, threaded=True)
```suggestion
    serve(app, host='0.0.0.0', port=8083)
```

2021-09-07 14:45 UTC, urasakikeisuke approved these changes
~LGTM~

2021-09-08 12:34 UTC, urasakikeisuke requested changes

2021-09-08 12:34 UTC, urasakikeisuke commented on aicon/frontend/templates/aicon.html
> +                  <input id="indeterminate-checkbox" type="checkbox" />
ユニークなidに変更してください

2021-09-08 12:34 UTC, urasakikeisuke commented on aicon/frontend/templates/aicon.html
> +                  <input id="indeterminate-checkbox" type="checkbox" />
ユニークなidに変更してください

2021-09-09 04:09 UTC, nakajima-john-shotaro commented on aicon/frontend/templates/aicon.html
> +                  <input id="indeterminate-checkbox" type="checkbox" />
Done. 👍

2021-09-09 04:20 UTC, urasakikeisuke approved these changes

2021-09-09 11:16 UTC, urasakikeisuke approved these changes

2021-09-09 11:18 UTC, merged